-- Supabase SQL Editor example for creating the admin auth user.
-- Do not commit a real production password in this file.
--
-- App login:
-- username: orionadmin
-- email generated by the app: orionadmin@orionkamp.local
--
-- Before running, replace CHANGE_ME_STRONG_PASSWORD with the real password.

create extension if not exists pgcrypto;

do $$
declare
  admin_email text := 'orionadmin@orionkamp.local';
  admin_password text := 'CHANGE_ME_STRONG_PASSWORD';
  admin_user_id uuid;
begin
  select id
  into admin_user_id
  from auth.users
  where email = admin_email;

  if admin_user_id is null then
    admin_user_id := gen_random_uuid();

    insert into auth.users (
      instance_id,
      id,
      aud,
      role,
      email,
      encrypted_password,
      email_confirmed_at,
      invited_at,
      confirmation_token,
      confirmation_sent_at,
      recovery_token,
      recovery_sent_at,
      email_change_token_new,
      email_change,
      email_change_sent_at,
      last_sign_in_at,
      raw_app_meta_data,
      raw_user_meta_data,
      is_super_admin,
      created_at,
      updated_at,
      phone,
      phone_confirmed_at,
      phone_change,
      phone_change_token,
      phone_change_sent_at,
      email_change_token_current,
      email_change_confirm_status,
      banned_until,
      reauthentication_token,
      reauthentication_sent_at
    )
    values (
      '00000000-0000-0000-0000-000000000000',
      admin_user_id,
      'authenticated',
      'authenticated',
      admin_email,
      crypt(admin_password, gen_salt('bf')),
      now(),
      null,
      '',
      null,
      '',
      null,
      '',
      '',
      null,
      null,
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"username":"orionadmin","role":"admin"}'::jsonb,
      false,
      now(),
      now(),
      null,
      null,
      '',
      '',
      null,
      '',
      0,
      null,
      '',
      null
    );
  else
    update auth.users
    set encrypted_password = crypt(admin_password, gen_salt('bf')),
        email_confirmed_at = coalesce(email_confirmed_at, now()),
        aud = 'authenticated',
        role = 'authenticated',
        raw_app_meta_data = '{"provider":"email","providers":["email"]}'::jsonb,
        raw_user_meta_data =
          coalesce(raw_user_meta_data, '{}'::jsonb) || '{"username":"orionadmin","role":"admin"}'::jsonb,
        updated_at = now()
    where id = admin_user_id;
  end if;

  if exists (
    select 1
    from auth.identities
    where user_id = admin_user_id
      and provider = 'email'
  ) then
    update auth.identities
    set provider_id = admin_user_id::text,
        identity_data = jsonb_build_object(
          'sub',
          admin_user_id::text,
          'email',
          admin_email,
          'email_verified',
          true,
          'phone_verified',
          false
        ),
        updated_at = now()
    where user_id = admin_user_id
      and provider = 'email';
  else
    insert into auth.identities (
      provider_id,
      user_id,
      identity_data,
      provider,
      last_sign_in_at,
      created_at,
      updated_at
    )
    values (
      admin_user_id::text,
      admin_user_id,
      jsonb_build_object(
        'sub',
        admin_user_id::text,
        'email',
        admin_email,
        'email_verified',
        true,
        'phone_verified',
        false
      ),
      'email',
      now(),
      now(),
      now()
    );
  end if;
end $$;
